name: CloudSim AWS Lambda Simulation CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run tests
      run: mvn test
      
    - name: Store JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: cloudsim-lambda-simulation-jar
        path: target/*.jar
        
    - name: Generate execution report
      run: |
        mkdir -p reports
        java -jar target/*.jar > reports/simulation-output.txt
      
    - name: Store report artifact
      uses: actions/upload-artifact@v3
      with:
        name: simulation-report
        path: reports/